//! # Rust Interface Design (Oculomotor)
//! 
//! This document outlines how the Rust `Oculomotor` component drives the eBPF sampler.
//! 
//! ## 1. Lifecycle Management
//! 
//! The `Oculomotor` struct owns the `SamplerSkel` (skeleton) generated by `libbpf-rs`.
//! 
//! ```rust
//! pub struct Oculomotor {
//!     skel: SamplerSkel<'static>,
//!     ringbuf: RingBuffer<'static>,
//!     hw_counters: HardwareCounters,
//!     // ...
//! }
//! ```
//! 
//! ### Initialization
//! 1.  **Open**: `SamplerSkelBuilder::default().open()?`
//! 2.  **Config**: Set `target_pid` on `skel.maps.bss_data`.
//! 3.  **Load**: `skel.load()?`
//! 4.  **Attach**: `skel.attach()?`
//! 
//! ## 2. Configuration Interface
//! 
//! We expose methods to update the "Control Channel" (Global Variables).
//! 
//! ```rust
//! impl Oculomotor {
//!     pub fn set_target_pid(&mut self, pid: u32) {
//!         if let Some(bss) = self.skel.maps.bss_data.as_mut() {
//!             bss.target_pid = pid;
//!         }
//!     }
//! 
//!     pub fn set_sample_rate(&mut self, interval_ns: u64) {
//!         if let Some(data) = self.skel.maps.data_data.as_mut() {
//!             data.min_sample_interval_ns = interval_ns;
//!         }
//!     }
//! }
//! ```
//! 
//! ## 3. Hardware Counter Management
//! 
//! The `HardwareCounters` struct manages the `perf_event` file descriptors and BPF map updates.
//! 
//! ### The `update_slot` method
//! When the `Scheduler` requests a new event for a slot:
//! 
//! 1.  **Create**: Open new `perf_event` FDs for *each* CPU for the requested event.
//! 2.  **Map Update**: 
//!     *   The BPF map `counters` is a `PERF_EVENT_ARRAY` sized `MAX_COUNTERS * MAX_CPUS`.
//!     *   For each CPU `c` and slot `i`:
//!         *   Calculate index: `idx = (c * MAX_COUNTERS) + i`.
//!         *   Update map at `idx` with the FD for that CPU.
//!         *   **Note**: This update must be performed with thread affinity set to the target CPU to ensure correct `perf_event` association in the kernel.
//! 
//! ## 4. Data Ingestion
//! 
//! ```rust
//! impl Oculomotor {
//!     pub fn poll(&self) -> Result<(), Box<dyn std::error::Error>> {
//!         // Polls the ring buffer.
//!         self.ringbuf.poll(Duration::from_millis(1))?;
//!         Ok(())
//!     }
//! }
//! ```
//! 
//! ## Summary of Flow
//! 
//! 1.  **User**: `saccade run --target-pid 123`
//! 2.  **Main**: `Oculomotor::new(123)` -> Loads BPF.
//! 3.  **Main Loop**:
//!     *   `oculomotore.step()`:
//!         *   `poll()` -> Consumes samples from ringbuf.
//!         *   `scheduler.next_step()` -> Returns `active_events`.
//!         *   `oculomotor.update_counters(active_events)` -> Updates hardware counters via `HardwareCounters`.
//! 
