//! # Rust Interface Design (Oculomotor)
//!
//! This document outlines how the Rust `Oculomotor` component drives the eBPF sampler.
//!
//! ## 1. Lifecycle Management
//!
//! The `Oculomotor` struct owns the `SamplerSkel` (skeleton) generated by `libbpf-rs`.
//!
//! ```ignore
//! pub struct Oculomotor {
//!     skel: SamplerSkel<'static>,
//!     ringbuf: RingBuffer<'static>,
//!     scheduler: Box<dyn Scheduler>,
//!     active_set: Vec<EventId>,      // currently scheduled events
//!     hw_counters: HardwareCounters,
//!     // timer_links / timer_events kept alive for Drop
//! }
//! ```
//!
//! ### Initialization
//! 1.  **Open**: `SamplerSkelBuilder::default().open()?`
//! 2.  **Config**: Set `target_pid` on `skel.maps.bss_data`.
//! 3.  **Load**: `skel.load()?`
//! 4.  **Attach**: `skel.attach()?`
//!
//! ## 2. Configuration Interface
//!
//! We expose methods to update the "Control Channel" (Global Variables).
//!
//! ```ignore
//! impl Oculomotor {
//!     pub fn set_target_pid(&mut self, pid: u32) {
//!         if let Some(bss) = self.skel.maps.bss_data.as_mut() {
//!             bss.target_pid = pid;
//!         }
//!     }
//!
//!     pub fn set_sample_rate(&mut self, interval_ns: u64) {
//!         if let Some(data) = self.skel.maps.data_data.as_mut() {
//!             data.min_sample_interval_ns = interval_ns;
//!         }
//!     }
//! }
//! ```
//!
//! ## 3. Hardware Counter Management
//!
//! The `HardwareCounters` struct manages the `perf_event` file descriptors and BPF map updates.
//!
//! ### The `update_slot` method
//! When `Oculomotor` requests a new event for a slot:
//!
//! 1.  **World-stop**: Set `tracking = false` in BPF globals; spin until all
//!     CPUs set their `stopped[cpu]` flag.
//! 2.  **Disable**: Call `disable()` on the old `perf_event` FD for the slot
//!     on each CPU (if one exists).
//! 3.  **Create & Enable**: Open a new `perf_event` FD per CPU for the
//!     requested event and immediately call `enable()`.
//! 4.  **Map Update**: For each CPU `c` and slot `i`, update BPF map
//!     `bpf_maps[i]` at key `c` with the new FD.
//! 5.  **Resume**: Set `tracking = true` in BPF globals.
//!
//! ## 4. Data Ingestion
//!
//! ```ignore
//! impl Oculomotor {
//!     pub fn poll(&self) -> Result<(), Box<dyn std::error::Error>> {
//!         // Polls the ring buffer.
//!         self.ringbuf.poll(Duration::from_millis(10))?;
//!         Ok(())
//!     }
//! }
//! ```
//!
//! ## Summary of Flow
//!
//! 1.  **User**: `saccade run -- <target> [args...]`
//! 2.  **Main**: Spawns the target process under ptrace, then calls
//!     `Oculomotor::new(pid, ...)` which loads and attaches the BPF programs.
//! 3.  **Main Loop**:
//!     *   `oculomotor.step()`:
//!         *   `poll()` -> Consumes samples from ringbuf, forwards to logger.
//!         *   `scheduler.next_step()` -> Returns `ScheduleDecision`.
//!         *   `oculomotor.update_counters(&decision)` -> Updates hardware counters via `HardwareCounters` for any slots whose event changed.
//!
