//! Blocking HTTP client for the Ollama `/api/chat` endpoint.

use serde::{Deserialize, Serialize};
use std::time::Duration;

/// Errors that can arise when sending a request to the inference server.
#[derive(Debug)]
pub enum LlmError {
    /// The HTTP request failed (connection refused, timeout, non-2xx status, etc.).
    Http(String),
    /// Serializing the request body to JSON failed.
    Json(serde_json::Error),
    /// The response body arrived but could not be parsed as an expected chat response.
    BadResponse(String),
}

impl std::fmt::Display for LlmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LlmError::Http(e) => write!(f, "HTTP error: {e}"),
            LlmError::Json(e) => write!(f, "JSON error: {e}"),
            LlmError::BadResponse(s) => write!(f, "bad LLM response: {s}"),
        }
    }
}

impl std::error::Error for LlmError {}

/// A single message in a chat conversation, compatible with the Ollama message schema.
#[derive(Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Conversation role: `"system"`, `"user"`, or `"assistant"`.
    pub role: String,
    /// Text content of the message.
    pub content: String,
}

/// Wire type for the `POST /api/chat` request body.
#[derive(Serialize)]
struct ChatRequest<'a> {
    /// Model identifier forwarded verbatim to Ollama.
    model: &'a str,
    /// Ordered message history for the conversation.
    messages: &'a [ChatMessage],
    /// Must be `false`; streaming responses are not supported by this client.
    stream: bool,
}

/// Top-level wrapper in the `POST /api/chat` response body.
#[derive(Deserialize)]
struct ChatResponse {
    /// The assistant turn produced by the model.
    message: ChatResponseMessage,
}

/// The assistant message object nested inside [`ChatResponse`].
#[derive(Deserialize)]
struct ChatResponseMessage {
    /// Text generated by the model.
    content: String,
}

/// Blocking HTTP client that sends chat requests to an Ollama-compatible inference server.
#[derive(Clone)]
pub struct LlmClient {
    /// Server root URL, trailing slash stripped, e.g. `http://host:11434`.
    base_url: String,
    /// Model name passed to the server with every request, e.g. `"gemma4"`.
    model: String,
    /// Underlying HTTP agent with pre-configured connect and response timeouts.
    agent: ureq::Agent,
}

impl LlmClient {
    /// Creates a client targeting `base_url` with a 10 s connect timeout and 120 s response timeout.
    pub fn new(base_url: &str, model: &str) -> Self {
        let config = ureq::Agent::config_builder()
            .timeout_connect(Some(Duration::from_secs(10)))
            .timeout_recv_response(Some(Duration::from_secs(120)))
            .build();
        Self {
            base_url: base_url.trim_end_matches('/').to_string(),
            model: model.to_string(),
            agent: config.into(),
        }
    }

    /// Returns the model name this client was configured with.
    pub fn model(&self) -> &str {
        &self.model
    }

    /// Blocking chat round-trip to `POST /api/chat`. Returns the assistant's reply text.
    pub fn chat(&self, messages: &[ChatMessage]) -> Result<String, LlmError> {
        let url = format!("{}/api/chat", self.base_url);
        let body = serde_json::to_vec(&ChatRequest {
            model: &self.model,
            messages,
            stream: false,
        })
        .map_err(LlmError::Json)?;

        let mut response = self
            .agent
            .post(&url)
            .header("Content-Type", "application/json")
            .send(body)
            .map_err(|e: ureq::Error| LlmError::Http(e.to_string()))?;

        let text = response
            .body_mut()
            .read_to_string()
            .map_err(|e: ureq::Error| LlmError::Http(e.to_string()))?;

        serde_json::from_str::<ChatResponse>(&text)
            .map(|parsed| parsed.message.content)
            .map_err(|_| LlmError::BadResponse(text))
    }
}
