//! Shared utilities for LLM-based scheduler implementations: prompt construction, JSON parsing,
//! and a retry loop that feeds malformed responses back to the model for correction.

use crate::event::EventId;
use crate::llm::{ChatMessage, LlmClient, LlmError, PromptBuilder};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

/// One step in a cyclic counter rotation schedule generated by the LLM.
#[derive(Debug, Deserialize, Serialize)]
pub(super) struct ScheduleStep {
    /// How long (in milliseconds) to hold this set of counters active.
    pub(super) duration_ms: u64,
    /// The hardware event IDs to activate during this step.
    pub(super) events: Vec<EventId>,
}

/// LLM-assigned sampling priority for a single hardware event.
#[derive(Debug, Deserialize, Serialize)]
pub(super) struct EventWeight {
    /// The hardware event this weight applies to.
    pub(super) event_id: EventId,
    /// Relative sampling priority in the range 1–10 (higher = sampled more often).
    pub(super) weight: u32,
}

/// JSON Schema for the structured-output schedule response: `{"steps": [{duration_ms, events}]}`.
///
/// `num_slots` is injected as `minItems`/`maxItems` on the `events` array and `valid_ids` as an
/// `enum` on each item so Ollama's constrained-decoding grammar enforces both count and ID range.
pub(super) fn schedule_json_schema(num_slots: usize, valid_ids: &[EventId]) -> serde_json::Value {
    serde_json::json!({
        "type": "object",
        "properties": {
            "steps": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "duration_ms": {"type": "integer"},
                        "events": {
                            "type": "array",
                            "items": {"type": "integer", "enum": valid_ids},
                            "minItems": num_slots,
                            "maxItems": num_slots
                        }
                    },
                    "required": ["duration_ms", "events"],
                    "additionalProperties": false
                }
            }
        },
        "required": ["steps"],
        "additionalProperties": false
    })
}

/// JSON Schema for the structured-output weights response: `{"weights": [{event_id, weight}]}`.
///
/// `valid_ids` is injected as an `enum` on `event_id` so the model cannot hallucinate IDs.
pub(super) fn weights_json_schema(valid_ids: &[EventId]) -> serde_json::Value {
    serde_json::json!({
        "type": "object",
        "properties": {
            "weights": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "event_id": {"type": "integer", "enum": valid_ids},
                        "weight": {"type": "integer"}
                    },
                    "required": ["event_id", "weight"],
                    "additionalProperties": false
                }
            }
        },
        "required": ["weights"],
        "additionalProperties": false
    })
}

#[derive(Deserialize)]
struct ScheduleResponse {
    steps: Vec<ScheduleStep>,
}

#[derive(Deserialize)]
struct WeightsResponse {
    weights: Vec<EventWeight>,
}

/// Build a compact few-shot schedule example using the first real event IDs.
///
/// Returns a pretty-printed `{"steps": [...]}` JSON string with 3 steps that deliberately
/// demonstrate a NON-uniform, tilted schedule: the first event (high-priority) recurs across
/// multiple steps with varying durations, while distinct counters fill the remaining slots.
/// The model imitates this shape rather than a flat round-robin.
pub(super) fn build_schedule_example(
    event_info: &[(EventId, String, String)],
    num_slots: usize,
) -> String {
    if event_info.is_empty() || num_slots == 0 {
        return r#"{"steps": []}"#.to_string();
    }
    let ids: Vec<EventId> = event_info.iter().map(|(id, _, _)| *id).collect();

    // Three steps with deliberately varied durations — high-priority counter (ids[0]) recurs.
    // Step durations vary to illustrate that important counters warrant longer observation windows.
    let durations = [100u64, 25, 75];
    let steps: Vec<serde_json::Value> = (0..3)
        .map(|i| {
            let mut step_ids: Vec<EventId> = Vec::with_capacity(num_slots);
            // Always include the first event (simulating a "high-value" counter that recurs).
            step_ids.push(ids[0]);
            // Fill remaining slots with different events, advancing offset per step.
            let offset = 1 + i * (num_slots.saturating_sub(1));
            for k in 0..num_slots.saturating_sub(1) {
                let idx = (offset + k) % ids.len();
                let candidate = ids[idx];
                // Avoid duplicating ids[0] if the wrap brings us back to it.
                if candidate == ids[0] && num_slots > 1 {
                    step_ids.push(ids[(offset + k + 1) % ids.len()]);
                } else {
                    step_ids.push(candidate);
                }
            }
            step_ids.dedup();
            step_ids.truncate(num_slots);
            // Pad if needed (edge case: very few events).
            while step_ids.len() < num_slots {
                step_ids.push(ids[step_ids.len() % ids.len()]);
            }
            serde_json::json!({"duration_ms": durations[i], "events": step_ids})
        })
        .collect();
    serde_json::to_string_pretty(&serde_json::json!({"steps": steps}))
        .expect("static JSON serialization")
}

/// Build a compact few-shot weights example using the first four real event IDs.
///
/// Demonstrates the FULL 1–10 range including a low weight so the model learns to spread
/// weights broadly rather than clustering near one value (which produces round-robin behavior).
pub(super) fn build_weights_example(event_info: &[(EventId, String, String)]) -> String {
    if event_info.is_empty() {
        return r#"{"weights": []}"#.to_string();
    }
    // Spread across low–high to discourage flat clustering: 9, 6, 3, 1.
    let example_weights = [9u32, 6, 3, 1];
    let weights: Vec<serde_json::Value> = event_info
        .iter()
        .take(4)
        .zip(example_weights.iter())
        .map(|((id, _, _), &w)| serde_json::json!({"event_id": id, "weight": w}))
        .collect();
    serde_json::to_string_pretty(&serde_json::json!({"weights": weights}))
        .expect("static JSON serialization")
}

/// Build the LLM system message describing the profiler's counter-rotation role and slot count.
pub(super) fn system_message(num_slots: usize, guidance: Option<&str>) -> String {
    let guidance_suffix = guidance
        .map(|g| format!("\n\nUser guidance: {g}"))
        .unwrap_or_default();
    format!(
        "You are an expert Linux performance profiling assistant. \
         You generate hardware performance counter observation schedules \
         for a sampling profiler that activates {num_slots} \
         counters simultaneously. The profiler cycles through the schedule \
         indefinitely, rotating which counters are active to build a \
         complete picture of program behavior over time.{guidance_suffix}"
    )
}

/// Construct the initial prompt asking the LLM to generate a full cyclic counter schedule.
///
/// When `analysis` is `Some`, the prose reasoning is replayed as an assistant turn (it was the
/// model's own output), bracketed by user turns that invite the reasoning and then request the
/// structured schedule, so the model treats it as its own chain-of-thought rather than an external
/// instruction. Existing callers pass `None` → no change.
pub(super) fn build_init_prompt(
    event_info: &[(EventId, String, String)],
    num_slots: usize,
    guidance: Option<&str>,
    analysis: Option<&str>,
) -> PromptBuilder {
    let mut event_list = String::new();
    for (id, name, desc) in event_info {
        event_list.push_str(&format!("  {id}: {name} — {desc}\n"));
    }
    let system = system_message(num_slots, guidance);
    let user = format!(
        "\
Available performance counters (format — ID: name: description):
{event_list}
Generate a cyclic measurement schedule. Every counter must appear at least \
once across the full cycle — this coverage floor is mandatory. Within that \
constraint, bias the marginal budget (extra repetitions, longer durations) \
toward counters that reveal bottlenecks or are expected to be bursty, \
high-rate, or high-variance: cache misses, TLB pressure, branch \
mispredictions, memory stalls, and ratio denominators such as \
instructions and cpu-cycles. Important counters SHOULD recur across \
multiple steps. Uniform allocation is NOT required and is generally \
suboptimal — deliberately tilt the schedule.

Each step activates {num_slots} counters and runs for a specified \
duration (aim for 10–1000 ms per step; vary durations to give more \
observation time to high-priority steps). Each step must have \
duration_ms (milliseconds) and events (an array of exactly \
{num_slots} counter IDs). Use each event ID at most once per step. \
Use only event IDs from the list above."
    );
    let example = build_schedule_example(event_info, num_slots);
    let mut pb = PromptBuilder::new()
        .system(system)
        .user(user)
        .assistant(example);

    if let Some(prose) = analysis {
        // `prose` was produced by the assistant in the preceding reasoning call, so replay it as
        // an assistant turn — not a user turn — so the model treats it as its own chain-of-thought
        // rather than an external instruction. A user turn on either side preserves role alternation.
        pb = pb
            .user(
                "Good. First, reason through which counters matter most and how to allocate the \
                 sampling budget across the cycle.",
            )
            .assistant(prose.to_string())
            .user(
                "Now produce the full, deliberately-tilted schedule as JSON, following your \
                 reasoning above and covering ALL the counters listed.",
            );
    } else {
        pb = pb.user(
            "Good. Now produce the full, deliberately-tilted schedule covering ALL \
             the counters listed above — not just those in the example.",
        );
    }
    pb
}

/// Parse and validate a structured-output schedule response, filtering unknown event IDs,
/// deduplicating, truncating to `num_slots`, and clamping zero durations to 1 ms; returns `Err`
/// when any step has fewer than `num_slots` valid unique events after filtering (the retry loop
/// in `chat_with_retry` feeds this error back to the model for correction).
pub(super) fn parse_schedule_response(
    response: &str,
    all_events: &[EventId],
    num_slots: usize,
) -> Result<Vec<ScheduleStep>, String> {
    let steps = serde_json::from_str::<ScheduleResponse>(response)
        .map_err(|e| format!("failed to parse schedule JSON: {e}"))?
        .steps;

    if steps.is_empty() {
        return Err("LLM returned an empty schedule".to_string());
    }

    let valid_ids: HashSet<u32> = all_events.iter().copied().collect();
    let mut steps_out: Vec<ScheduleStep> = Vec::with_capacity(steps.len());
    for (i, mut step) in steps.into_iter().enumerate() {
        step.events.retain(|id| valid_ids.contains(id));
        let valid_count = step.events.len();
        step.events.sort_unstable();
        step.events.dedup();
        step.events.truncate(num_slots);
        step.duration_ms = step.duration_ms.max(1);

        // If duplicates in an otherwise-sufficient event list reduced the unique count below
        // num_slots, pad with unused valid events rather than retrying.
        if valid_count >= num_slots && step.events.len() < num_slots {
            let step_set: HashSet<EventId> = step.events.iter().copied().collect();
            let needed = num_slots - step.events.len();
            tracing::warn!(
                step = i,
                needed,
                "LLM step contained duplicate IDs; padding with unused events"
            );
            for &id in all_events.iter() {
                if step.events.len() == num_slots {
                    break;
                }
                if !step_set.contains(&id) {
                    step.events.push(id);
                }
            }
            step.events.sort_unstable();
        }

        if step.events.len() != num_slots {
            return Err(format!(
                "step {i} has {} valid unique event IDs, need exactly {num_slots}",
                step.events.len()
            ));
        }
        steps_out.push(step);
    }

    Ok(steps_out)
}

/// Construct the prompt asking the LLM to assign a 1–10 priority weight to every available event.
pub(super) fn build_weights_prompt(
    event_info: &[(EventId, String, String)],
    num_slots: usize,
    guidance: Option<&str>,
) -> PromptBuilder {
    let mut event_list = String::new();
    for (id, name, desc) in event_info {
        event_list.push_str(&format!("  {id}: {name} — {desc}\n"));
    }
    let system = system_message(num_slots, guidance);
    let user = format!(
        "Available performance counters (format — ID: name: description):
{event_list}
Assign a priority weight (integer 1–10) to each counter based on its \
expected information value. Use the FULL 1–10 range — do NOT cluster \
all counters near one value, as that degrades to round-robin sampling. \
Rank higher (8–10) counters that are bursty, high-variance, or form \
critical ratio denominators — cpu-cycles, instructions, cache misses, \
branch mispredictions, TLB misses, and memory stalls. Rank lower (1–3) \
counters that are stable, low-rate, or redundant given others already \
measured. Every counter must appear exactly once in your response. \
Use only event IDs from the list above."
    );
    let example = build_weights_example(event_info);
    PromptBuilder::new()
        .system(system)
        .user(user)
        .assistant(example)
        .user(
            "Good. Now produce the COMPLETE weights list for ALL the counters listed above, \
             using the full 1–10 range with meaningful differentiation.",
        )
}

/// Parse a structured-output weights response, clamping values to 1–10, deduplicating by
/// keeping the maximum weight, and filling any missing events with weight 1.
pub(super) fn parse_weights_response(
    response: &str,
    all_events: &[EventId],
) -> Result<Vec<EventWeight>, String> {
    let parsed = serde_json::from_str::<WeightsResponse>(response)
        .map_err(|e| format!("failed to parse weights JSON: {e}"))?
        .weights;

    let valid_ids: HashSet<EventId> = all_events.iter().copied().collect();
    let mut by_id: HashMap<EventId, u32> = HashMap::new();
    for ew in parsed {
        if valid_ids.contains(&ew.event_id) {
            let w = ew.weight.clamp(1, 10);
            by_id
                .entry(ew.event_id)
                .and_modify(|v| *v = (*v).max(w))
                .or_insert(w);
        }
    }

    for &id in all_events {
        by_id.entry(id).or_insert(1);
    }

    if by_id.is_empty() {
        return Err("no valid event weights in response".to_string());
    }
    Ok(by_id
        .into_iter()
        .map(|(event_id, weight)| EventWeight { event_id, weight })
        .collect())
}

/// Construct a free-form (no JSON schema) prompt asking the model to analyze which counters
/// matter and why, as a prelude to structured schedule generation.
///
/// The returned `PromptBuilder` should be sent via [`LlmClient::chat_freeform`]; the resulting
/// prose is then passed as `analysis` to [`build_init_prompt`] or [`build_update_prompt`].
pub(super) fn build_reasoning_prompt(
    event_info: &[(EventId, String, String)],
    num_slots: usize,
    guidance: Option<&str>,
) -> PromptBuilder {
    let mut event_list = String::new();
    for (id, name, desc) in event_info {
        event_list.push_str(&format!("  {id}: {name} — {desc}\n"));
    }
    let system = system_message(num_slots, guidance);
    let user = format!(
        "\
Available performance counters (format — ID: name: description):
{event_list}
Before generating a schedule, analyze these counters in prose. Consider:
1. Which counters are likely bursty or high-variance (spiky event rates)?
2. Which counters form meaningful pairs or ratios (e.g. misses/references, \
   instructions/cycles) that must be co-sampled to be interpretable?
3. Which counters are ratio denominators (cpu-cycles, instructions, \
   cache-references) and therefore especially important to sample frequently?
4. Which counters are stable, low-rate, or redundant given others?
5. Given {num_slots} simultaneous slots, what allocation strategy would \
   maximize information gain — which counters deserve to recur, and which \
   are lower priority?

Do NOT produce JSON. Reason freely in prose; the schedule will be generated \
in the next step based on your analysis."
    );
    PromptBuilder::new().system(system).user(user)
}

/// Generate a counter-rotation schedule via LLM, optionally preceded by a free-form reasoning call.
#[allow(clippy::too_many_arguments)]
///
/// When `reasoning` is `true`, first calls [`LlmClient::chat_freeform`] with
/// [`build_reasoning_prompt`] to obtain a prose analysis, then weaves that analysis into
/// [`build_init_prompt`] as an extra user turn before the structured call.
/// When `reasoning` is `false`, calls [`build_init_prompt`] directly with `analysis = None`.
///
/// `call_type` labels the structured chat call in latency logs; the freeform reasoning call is
/// logged as `"{call_type}_reason"`. `sampled_latency_ms` applies only to the structured call
/// (simulation latency accounting does not cover the reasoning call).
pub(super) fn generate_schedule(
    client: &LlmClient,
    event_info: &[(EventId, String, String)],
    all_events: &[EventId],
    num_slots: usize,
    guidance: Option<&str>,
    reasoning: bool,
    call_type: &str,
    sampled_latency_ms: Option<u64>,
) -> Result<Vec<ScheduleStep>, Box<dyn std::error::Error>> {
    let analysis: Option<String> = if reasoning {
        let reason_type = format!("{call_type}_reason");
        let pb = build_reasoning_prompt(event_info, num_slots, guidance);
        tracing::debug!(
            "generate_schedule reasoning prompt:\n{}",
            pb.build()[0].content
        );
        match client.chat_freeform(pb.build(), &reason_type, None) {
            Ok(text) => {
                tracing::debug!("generate_schedule reasoning response:\n{text}");
                Some(text)
            }
            Err(e) => {
                tracing::warn!(
                    "generate_schedule reasoning call failed: {e}; proceeding without analysis"
                );
                None
            }
        }
    } else {
        None
    };

    let pb = build_init_prompt(event_info, num_slots, guidance, analysis.as_deref());
    tracing::debug!(
        "generate_schedule system message:\n{}",
        pb.build()[0].content
    );
    let messages = pb.build().to_vec();
    let schema = schedule_json_schema(num_slots, all_events);
    chat_with_retry(
        |m| client.chat(m, "schedule", &schema, call_type, sampled_latency_ms),
        messages,
        |resp| parse_schedule_response(resp, all_events, num_slots),
        2,
    )
}

/// Strip trailing newline-separated context from parse error messages before echoing to the LLM.
fn error_reason(err: &str) -> &str {
    if let Some(i) = err.find(":\n") {
        return &err[..i];
    }
    err
}

/// Send `initial_messages` to `chat_fn` and parse with `parse`, feeding malformed responses back
/// as assistant turns with a correction prompt for up to `max_retries` retries; HTTP errors abort immediately.
pub(super) fn chat_with_retry<T>(
    mut chat_fn: impl FnMut(&[ChatMessage]) -> Result<String, LlmError>,
    initial_messages: Vec<ChatMessage>,
    parse: impl Fn(&str) -> Result<T, String>,
    max_retries: usize,
) -> Result<T, Box<dyn std::error::Error>> {
    let mut messages = initial_messages;
    for attempt in 0..=max_retries {
        for (i, msg) in messages.iter().enumerate() {
            tracing::debug!(
                "LLM request [attempt={} msg={}] role={}\n{}",
                attempt,
                i,
                msg.role,
                msg.content
            );
        }
        let response = chat_fn(&messages)?;
        tracing::debug!("LLM response [attempt={}]\n{}", attempt, response);
        match parse(&response) {
            Ok(result) => return Ok(result),
            Err(err) => {
                let reason = error_reason(&err);
                tracing::warn!("LLM parse attempt {}: {reason}", attempt + 1);
                if attempt == max_retries {
                    return Err(Box::new(std::io::Error::other(err)));
                }
                // Only include the bad response as an assistant turn when it is non-empty.
                // An empty assistant turn confuses instruction-tuned models and can cause them
                // to return empty output on subsequent attempts.
                if !response.is_empty() {
                    messages.push(ChatMessage {
                        role: "assistant".into(),
                        content: response,
                    });
                }
                messages.push(ChatMessage {
                    role: "user".into(),
                    content: format!(
                        "Your response contained an error: {reason}\n\
                         Fix the error and respond again."
                    ),
                });
            }
        }
    }
    unreachable!()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::llm::LlmError;

    /// A fixed set of five event IDs used as a common test fixture.
    fn events() -> Vec<EventId> {
        vec![0, 1, 2, 3, 4]
    }

    /// Wrap a string as a user-role `ChatMessage`.
    fn user_msg(content: &str) -> ChatMessage {
        ChatMessage {
            role: "user".into(),
            content: content.into(),
        }
    }

    #[test]
    fn retry_succeeds_on_first_attempt() {
        let json = r#"{"steps": [{"duration_ms": 10, "events": [0]}]}"#;
        let mut calls = 0usize;
        let result = chat_with_retry(
            |_m| {
                calls += 1;
                Ok(json.to_string())
            },
            vec![user_msg("go")],
            |resp| parse_schedule_response(resp, &[0], 1),
            2,
        );
        assert!(result.is_ok());
        assert_eq!(calls, 1);
    }

    #[test]
    fn retry_feeds_back_and_succeeds_on_second_attempt() {
        let responses = std::cell::RefCell::new(vec![
            "not json at all".to_string(),
            r#"{"steps": [{"duration_ms": 10, "events": [0]}]}"#.to_string(),
        ]);
        let mut calls = 0usize;
        let result = chat_with_retry(
            |m| {
                calls += 1;
                if calls > 1 {
                    // Second call should include the bad assistant turn and correction prompt.
                    assert!(m.iter().any(|msg| msg.role == "assistant"));
                    assert!(m.iter().any(
                        |msg| msg.role == "user" && msg.content.contains("contained an error")
                    ));
                }
                Ok(responses.borrow_mut().remove(0))
            },
            vec![user_msg("go")],
            |resp| parse_schedule_response(resp, &[0], 1),
            2,
        );
        assert!(result.is_ok());
        assert_eq!(calls, 2);
    }

    #[test]
    fn retry_exhausted_returns_err() {
        let result: Result<Vec<ScheduleStep>, _> = chat_with_retry(
            |_m| Ok(r#"{"steps": []}"#.to_string()),
            vec![user_msg("go")],
            |resp| parse_schedule_response(resp, &[0], 4),
            2,
        );
        assert!(result.is_err());
    }

    #[test]
    fn retry_http_error_propagates_immediately() {
        let mut calls = 0usize;
        let result: Result<Vec<ScheduleStep>, _> = chat_with_retry(
            |_m| {
                calls += 1;
                Err(LlmError::Http("timeout".into()))
            },
            vec![user_msg("go")],
            |resp| parse_schedule_response(resp, &[0], 4),
            5,
        );
        assert!(result.is_err());
        assert_eq!(calls, 1, "should not retry on HTTP error");
    }

    #[test]
    fn error_reason_strips_trailing_context() {
        // Strips context after ":\n" (e.g. a multi-line serde_json error).
        let err = "outer reason:\ninner detail";
        assert_eq!(error_reason(err), "outer reason");

        // Passes through errors without ":\n" unchanged.
        let err2 = "step 0 has 1 valid unique event IDs, need exactly 4";
        assert_eq!(error_reason(err2), err2);

        let err3 = "LLM returned an empty schedule";
        assert_eq!(error_reason(err3), "LLM returned an empty schedule");
    }

    #[test]
    fn system_message_includes_guidance() {
        let msg = system_message(4, Some("focus on memory bandwidth"));
        assert!(msg.contains("focus on memory bandwidth"));
    }

    #[test]
    fn system_message_no_guidance() {
        let msg = system_message(4, None);
        assert!(!msg.contains("User guidance"));
    }

    #[test]
    fn parse_valid_schedule() {
        let json = r#"{"steps": [
            {"duration_ms": 25, "events": [0, 1, 2, 3]},
            {"duration_ms": 30, "events": [1, 2, 3, 4]}
        ]}"#;
        let steps = parse_schedule_response(json, &events(), 4).unwrap();
        assert_eq!(steps.len(), 2);
        assert_eq!(steps[0].duration_ms, 25);
        assert_eq!(steps[0].events, vec![0, 1, 2, 3]);
        assert_eq!(steps[1].events, vec![1, 2, 3, 4]);
    }

    #[test]
    fn parse_invalid_json_errors() {
        let err = parse_schedule_response("the model just said hello", &events(), 4).unwrap_err();
        assert!(err.contains("failed to parse schedule JSON"), "got: {err}");
    }

    #[test]
    fn parse_empty_steps_errors() {
        let err = parse_schedule_response(r#"{"steps": []}"#, &events(), 4).unwrap_err();
        assert!(err.contains("empty"));
    }

    #[test]
    fn parse_filters_invalid_ids() {
        let json = r#"{"steps": [{"duration_ms": 20, "events": [0, 99]}]}"#;
        let steps = parse_schedule_response(json, &[0, 1], 1).unwrap();
        assert_eq!(steps[0].events, vec![0]);
    }

    #[test]
    fn parse_all_invalid_ids_errors() {
        let json = r#"{"steps": [{"duration_ms": 20, "events": [99, 100]}]}"#;
        let err = parse_schedule_response(json, &[0, 1], 4).unwrap_err();
        assert!(err.contains("0 valid unique event IDs"), "got: {err}");
    }

    #[test]
    fn parse_bad_step_causes_err() {
        // A step with no valid IDs triggers Err immediately; the retry loop handles correction.
        let json = r#"{"steps": [
            {"duration_ms": 20, "events": [99, 100]},
            {"duration_ms": 30, "events": [0, 1]}
        ]}"#;
        let err = parse_schedule_response(json, &[0, 1], 2).unwrap_err();
        assert!(err.contains("step 0"), "got: {err}");
    }

    #[test]
    fn parse_clamps_zero_duration() {
        let json = r#"{"steps": [{"duration_ms": 0, "events": [0]}]}"#;
        let steps = parse_schedule_response(json, &[0], 1).unwrap();
        assert_eq!(steps[0].duration_ms, 1);
    }

    #[test]
    fn parse_truncates_to_num_slots() {
        let json = r#"{"steps": [{"duration_ms": 10, "events": [0, 1, 2, 3, 4]}]}"#;
        let steps = parse_schedule_response(json, &events(), 2).unwrap();
        assert_eq!(steps[0].events.len(), 2);
    }

    #[test]
    fn parse_valid_weights() {
        let json = r#"{"weights": [{"event_id": 0, "weight": 5}, {"event_id": 1, "weight": 2}]}"#;
        let weights = parse_weights_response(json, &[0, 1]).unwrap();
        let map: HashMap<EventId, u32> = weights
            .into_iter()
            .map(|ew| (ew.event_id, ew.weight))
            .collect();
        assert_eq!(map[&0], 5);
        assert_eq!(map[&1], 2);
    }

    #[test]
    fn parse_weights_fills_missing_events() {
        let json = r#"{"weights": [{"event_id": 0, "weight": 5}]}"#;
        let weights = parse_weights_response(json, &[0, 1, 2]).unwrap();
        let map: HashMap<EventId, u32> = weights
            .into_iter()
            .map(|ew| (ew.event_id, ew.weight))
            .collect();
        assert_eq!(map[&0], 5);
        assert_eq!(map[&1], 1);
        assert_eq!(map[&2], 1);
    }

    #[test]
    fn parse_weights_clamps_out_of_range() {
        let json = r#"{"weights": [{"event_id": 0, "weight": 0}, {"event_id": 1, "weight": 15}]}"#;
        let weights = parse_weights_response(json, &[0, 1]).unwrap();
        let map: HashMap<EventId, u32> = weights
            .into_iter()
            .map(|ew| (ew.event_id, ew.weight))
            .collect();
        assert_eq!(map[&0], 1);
        assert_eq!(map[&1], 10);
    }

    #[test]
    fn parse_weights_filters_unknown_ids() {
        let json = r#"{"weights": [{"event_id": 0, "weight": 5}, {"event_id": 99, "weight": 8}]}"#;
        let weights = parse_weights_response(json, &[0, 1]).unwrap();
        let map: HashMap<EventId, u32> = weights
            .into_iter()
            .map(|ew| (ew.event_id, ew.weight))
            .collect();
        assert!(!map.contains_key(&99));
        assert_eq!(map[&0], 5);
        assert_eq!(map[&1], 1);
    }

    #[test]
    fn parse_weights_deduplicates_keeps_max() {
        let json = r#"{"weights": [{"event_id": 0, "weight": 3}, {"event_id": 0, "weight": 7}]}"#;
        let weights = parse_weights_response(json, &[0]).unwrap();
        let map: HashMap<EventId, u32> = weights
            .into_iter()
            .map(|ew| (ew.event_id, ew.weight))
            .collect();
        assert_eq!(map[&0], 7);
    }

    #[test]
    fn parse_weights_invalid_json_errors() {
        let err = parse_weights_response("hello world", &[0]).unwrap_err();
        assert!(err.contains("failed to parse weights JSON"), "got: {err}");
    }

    #[test]
    fn parse_step_too_short_returns_err() {
        let json = r#"{"steps": [{"duration_ms": 20, "events": [0, 99]}]}"#;
        let err = parse_schedule_response(json, &[0, 1, 2, 3], 4).unwrap_err();
        assert!(err.contains("step 0"), "got: {err}");
        assert!(err.contains("1 valid unique event IDs"), "got: {err}");
    }

    #[test]
    fn parse_pads_duplicates_when_enough_valid_ids() {
        // [0,0,1,2] has 4 valid IDs before dedup but only 3 unique; padding fills the 4th slot.
        let json = r#"{"steps": [{"duration_ms": 10, "events": [0, 0, 1, 2]}]}"#;
        let steps = parse_schedule_response(json, &[0, 1, 2, 3], 4).unwrap();
        assert_eq!(steps[0].events.len(), 4);
        // Must still be sorted and contain only valid IDs.
        assert!(steps[0].events.windows(2).all(|w| w[0] < w[1]));
        for id in &steps[0].events {
            assert!([0u32, 1, 2, 3].contains(id));
        }
    }

    #[test]
    fn parse_duplicates_removed_when_unique_count_matches() {
        // Duplicates removed and result has exactly num_slots unique events → Ok.
        let json = r#"{"steps": [{"duration_ms": 10, "events": [0, 0, 1, 2, 3]}]}"#;
        let steps = parse_schedule_response(json, &[0, 1, 2, 3], 4).unwrap();
        assert_eq!(steps[0].events, vec![0, 1, 2, 3]);
    }

    #[test]
    fn build_reasoning_prompt_contains_analysis_keys() {
        let event_info = vec![
            (0u32, "cache-misses".to_string(), "Cache misses".to_string()),
            (1u32, "cpu-cycles".to_string(), "CPU cycles".to_string()),
        ];
        let pb = build_reasoning_prompt(&event_info, 2, None);
        let messages = pb.build();
        // Should have a system message and a user message.
        assert!(messages.len() >= 2);
        let user = messages.iter().find(|m| m.role == "user").unwrap();
        // Prompt should ask for prose analysis and mention burstiness, ratios, etc.
        assert!(user.content.contains("bursty"));
        assert!(user.content.contains("JSON"));
        assert!(user.content.contains("cache-misses"));
    }

    #[test]
    fn build_init_prompt_replays_analysis_as_assistant_turn() {
        // The reasoning prose must appear as an ASSISTANT turn (it was the model's own output),
        // not be quoted back as user text, and the final turn must be a user request for the
        // schedule that does NOT contain the prose.
        let event_info = vec![(0u32, "cache-misses".to_string(), "Cache misses".to_string())];
        let with = build_init_prompt(&event_info, 1, None, Some("focus on cache"))
            .build()
            .to_vec();

        // The prose lives in an assistant turn, never in a user turn.
        let in_assistant = with
            .iter()
            .any(|m| m.role == "assistant" && m.content.contains("focus on cache"));
        assert!(in_assistant, "analysis prose should be an assistant turn");
        assert!(
            !with
                .iter()
                .any(|m| m.role == "user" && m.content.contains("focus on cache")),
            "analysis prose must not appear in any user turn"
        );

        // Final turn is a user request for the schedule that references the prior reasoning.
        let last = with.last().unwrap();
        assert_eq!(last.role, "user");
        assert!(last.content.contains("reasoning"));
        assert!(!last.content.contains("focus on cache"));

        // Roles alternate (no two consecutive turns share a role).
        assert!(
            with.windows(2).all(|w| w[0].role != w[1].role),
            "roles must alternate: {:?}",
            with.iter().map(|m| &m.role).collect::<Vec<_>>()
        );
    }

    #[test]
    fn build_schedule_example_first_id_recurs() {
        // With multiple events and num_slots=2, ids[0] should appear in every step.
        let event_info: Vec<(EventId, String, String)> = (0u32..5)
            .map(|i| (i, format!("event-{i}"), "desc".to_string()))
            .collect();
        let example = build_schedule_example(&event_info, 2);
        let parsed: serde_json::Value = serde_json::from_str(&example).unwrap();
        let steps = parsed["steps"].as_array().unwrap();
        assert!(!steps.is_empty());
        // ids[0] = 0 should appear in every step.
        for step in steps {
            let events = step["events"].as_array().unwrap();
            let has_first = events.iter().any(|v| v.as_u64() == Some(0));
            assert!(has_first, "step missing recurrent counter 0: {step}");
        }
    }
}
